### PR TITLE
Action to remove points

### PR DESCRIPTION
**Pull request by albfan**
Here a screencast for the feature:

Added shorcuts for zoom-in/zoom-out to ease the process

https://user-images.githubusercontent.com/220968/133135581-2d6e764c-1af1-499e-8f34-bf37351c5128.mp4

relates to #20

### CODE REVIEW

**Comment by DaveDavenport** [comment]
should we add a saving option?

**Comment by albfan** [comment]
Sure, But for view purposes I guess this is feature complete.

I want to open a new issue to support geojson and probably add writers for any format.

Let me know if you prefer to have that implemented or we can wait for that

**Comment by albfan** [comment]
#24 shows the task to save gpx is near, but has lot of corner cases.

I'd suggest to merge this (release 0.5.0) until export is ready (0.6.0 or 1.0.0)

We can create a roadmap in wiki if you prefer @DaveDavenport

**Comment by DaveDavenport** [comment]
I am very busy and even have less time then I hoped.  so I am currently perfectly happy if you want to take the reigns .

**Comment by albfan** [comment]
Sure. Will take care of it

**Pull request closed without merging**
