### PR TITLE
Export gpx

### PR DESCRIPTION
**Pull request by albfan**
TODO:

- [x] Use a save dialog (probably use standard dialogs all around
- [x] replace current active_route with saved one (track->path)
- [x] Disable export if no active_route is enabled
- [x] Add new file to recent files
- [x] Include some metadata in track
- [x] Read some metadata in a parent of track object (for global time, creator and other global data)
- [ ] Allow to change that metadata in GUI

### CODE REVIEW

**Comment by albfan** [comment]
This PR has derived into:

- Read all gpx info
- Save waypoints, routes and tracks
- Clean recent archive list
- Connect switches to see waypoints and graph points

This probably will override and miss some data (I see gpx with version 1.3 not documented anywhere that changes gpx attributes) but that can be refined later.

**Comment by DaveDavenport** [comment]
:partying_face:  I will look it over soon.

**Comment by albfan** [comment]
It ends in a mix of several things I found useful. I can split or you can cherry pick. I can rework anything you need

**Comment by DaveDavenport** [comment]
Seems to work well.  Can we export more information? like cadence and heart-rate?

**Comment by albfan** [comment]
Yes, let me rework It. Some gpx examples would help ( I can find elsewhere)

**Comment by DaveDavenport** [comment]
I need to look if I can find some. I tried it on a fit file from my watch, but that has a bit to much personal info :grin:

**Comment by albfan** [comment]
I splited this and merge what is working correctly

**Pull request closed without merging**
